### ISSUE TITLE
Hex Color SVP

### ISSUE THREAD

**Issue by DavidSimonRothschild** [srfdata/swiss-party-colors#22]
Die Hex -Farbe (#4B8A3E), die  bei der SVP verwendet wurde,  existiert nicht oder nicht mehr.

Ich konnte das Farbschema daher nicht replizieren.

**Comment by rsalzer** [comment]
Das ist ein Hex-Code, der existiert ... https://g.co/kgs/sGUuiy
Könntest Du das Problem genauer beschreiben?

**Comment by DavidSimonRothschild** [comment]
Problem hatt sich erledigt.

**Comment by DavidSimonRothschild** [comment]
Problem hat sich erledigt.
